# Generated by Django 5.1.1 on 2024-09-23 05:32

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tbl_city_tbl_jobs_tbl_slider_video_news_tbl_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_news',
            name='news_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video_news',
            name='news_description',
            field=tinymce.models.HTMLField(null=True),
        ),
    ]
